### ISSUE TITLE
Strip down the MEAN app to bare bones

### ISSUE THREAD

**Issue by SundayFunday** [CodeForCharlotte/adopt_a_node#19]
To prer for rebuild specific to our Adopt-a project.

**Comment by tannerhodges** [comment]
Hey, just wanted to follow up on this. Been busy -- planning to hit this up next week, though.

**Comment by SundayFunday** [comment]
Hey Tanner,

Great! Sorry for the radio silence. After last Monday I've been working 12 hour days non-stop (worst 1-2 weeks of work ever). I'm going to set a couple days this month to meet in addition to the code for Charlotte hack nights. Looking forward to working with you!

Chris
